<SCRIPT LANGUAGE="JavaScript">
var posx = new Array();
var posy = new Array();
</SCRIPT>

<!-- NIEUW -->
<DIV id="menu_2layer" style="position: absolute; visibility: hidden; z-index: 3; filter: alpha(opacity=85); -moz-opacity: 90%;" onmouseover="menuOver();" onmouseout="menuOut('menu_2layer');">
<TABLE class="submenutable" cellpadding="2" cellspacing="1">
	<tr><TD class="submenutd"><a href="default.asp?m=lid&a=nieuw" class="submenutd">Lid</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=nieuwsbrief&a=nieuw" class="submenutd">Nieuwsbrief</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=agenda&a=nieuw" class="submenutd">Agendapunt</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=ervaring&a=nieuw" class="submenutd">Ervaring</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=fotoalbum&a=nieuw" class="submenutd">Fotoalbum</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=kopfoto&a=nieuw" class="submenutd">Kopfoto</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=bestand&a=nieuw" class="submenutd">Bestand</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=bestuursjaar&a=nieuw" class="submenutd">Bestuursjaar</a></TD></tr>
</TABLE>
</DIV>
<SCRIPT LANGUAGE="JavaScript">
posx.menu_2layer = 110;
posy.menu_2layer = 113;
</SCRIPT>

<!-- OVERZICHT -->
<DIV id="menu_3layer" style="position: absolute; visibility: hidden; z-index: 3; filter: alpha(opacity=85); -moz-opacity: 90%;" onmouseover="menuOver();" onmouseout="menuOut('menu_3layer');">
<TABLE class="submenutable" cellpadding="2" cellspacing="1">
	<tr><TD class="submenutd"><a href="default.asp?m=ledenlijst&a=" class="submenutd">Leden</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=nieuwsbrief&a=" class="submenutd">Nieuwsbrieven</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=agenda&a=" class="submenutd">Agenda</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=ervaring&a=" class="submenutd">Ervaringen</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=fotoalbum&a=" class="submenutd">Fotoalbums</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=kopfoto&a=" class="submenutd">Kopfoto's</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=bestand&a=" class="submenutd">Bestanden</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=bestuursjaar&a=" class="submenutd">Bestuursjaren</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=referrer" class="submenutd">Referrers</a></TD></tr>
</TABLE>
</DIV>
<SCRIPT LANGUAGE="JavaScript">
posx.menu_3layer = 110;
posy.menu_3layer = 136;
</SCRIPT>

<!-- LEDENLIJST -->
<DIV id="menu_4layer" style="position: absolute; visibility: hidden; z-index: 3; filter: alpha(opacity=85); -moz-opacity: 90%;" onmouseover="menuOver();" onmouseout="menuOut('menu_4layer');">
<TABLE class="submenutable" cellpadding="2" cellspacing="1">
	<tr><TD class="submenutd"><a href="default.asp?m=ledenlijst&a=" class="submenutd">Overzicht</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=ledenlijst&a=nieuwsbrief" class="submenutd">In de Nieuwsbrief</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=ledenlijst&orderby=datum_aangemeld" class="submenutd">Gesorteerd op aanmelddatum</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=ledenlijst&a=ontvangers" class="submenutd">Nieuwsbrief ontvangers</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=ledenlijst&a=ehbo" class="submenutd">EHBO</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=ledenlijst&a=contributie" class="submenutd">Contributie</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=ledenlijst&a=skateweekend" class="submenutd">Skateweekend</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=ledenlijst&a=sbn" class="submenutd">SBN (skatebond)</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=ledenlijst&a=oudleden" class="submenutd">Incl. oud-leden</a></TD></tr>
</TABLE>
</DIV>
<SCRIPT LANGUAGE="JavaScript">
posx.menu_4layer = 110;
posy.menu_4layer = 159;
</SCRIPT>

<!-- TEKSTEN -->
<DIV id="menu_5layer" style="position: absolute; visibility: hidden; z-index: 3; filter: alpha(opacity=85); -moz-opacity: 90%;" onmouseover="menuOver();" onmouseout="menuOut('menu_5layer');">
<TABLE class="submenutable" cellpadding="2" cellspacing="1">
	<tr><TD class="submenutd"><a href="default.asp?m=tekst&a=1" class="submenutd">Homepagina</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=tekst&a=2" class="submenutd">Spelregels</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=tekst&a=3" class="submenutd">Vereniging</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=tekst&a=4" class="submenutd">Nieuwsbrief (e-mail)</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=tekst&a=5" class="submenutd">Nieuwsflits (e-mail)</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=tekst&a=6" class="submenutd">Nieuw lid (e-mail)</a></TD></tr>
</TABLE>
</DIV>
<SCRIPT LANGUAGE="JavaScript">
posx.menu_5layer = 110;
posy.menu_5layer = 185;
</SCRIPT>

<!-- E-MAIL -->
<DIV id="menu_6layer" style="position: absolute; visibility: hidden; z-index: 3; filter: alpha(opacity=85); -moz-opacity: 90%;" onmouseover="menuOver();" onmouseout="menuOut('menu_6layer');">
<TABLE class="submenutable" cellpadding="2" cellspacing="1">
	<tr><TD class="submenutd"><a href="default.asp?m=email&a=nieuwsbrief" class="submenutd">Nieuwsbrief</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=email&a=flitsmet" class="submenutd">Nieuwsflits met bijlage</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=email&a=flitszonder&ace=true" class="submenutd">Nieuwsflits zonder bijlage</a></TD></tr>
	<tr><TD class="submenutd"><a href="default.asp?m=email&a=" class="submenutd">Archief</a></TD></tr>
</TABLE>
</DIV>
<SCRIPT LANGUAGE="JavaScript">
posx.menu_6layer = 110;
posy.menu_6layer = 209;
</SCRIPT>

<script src="../inc/pulldown.js" type="text/javascript"></script>